Feature/config voltage
DigitalShoestringSolutions/PowerMonitoring pull request #25
Opened 2024-05-28 10:38 UTC by tobyaharris

Makes assumed voltage configurable in the same way as power factor.

2024-05-28 10:45 UTC, Greg-Hawkridge requested changes

2024-05-28 10:45 UTC, Greg-Hawkridge commented on analysis/config/user_config.toml
Add a comment above the `voltage_line_neutral` and `power_factor` sections explaining how to use them. Similar to what we do in the current_dc config

2024-05-28 11:10 UTC, tobyaharris commented on analysis/config/user_config.toml
Done. Our poor community platform instructions will soon have nothing left to offer!

2024-05-28 17:12 UTC, tobyaharris commented
This appears to work fine in a quick test on basic hardware: the values entered in `user_config.toml` are being used to calculated powers in the dashboard. The Intermediate test bench needs some hardware TLC. 
There is a now even more repetition in `electrical.py`, but that is another day's problem.

2024-06-05 09:26 UTC, Greg-Hawkridge approved these changes

2024-06-05 09:26 UTC, merged